version: '3.9'

services:
  db:
    image: 'postgres'
    ports:
      - '4321:5432'
    environment:
      POSTGRES_PASSWORD: '123456'
      POSTGRES_USER: 'docker'
  server:
    build: .
    ports:
      - '5000:5000'
    depends_on:
      - db